/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'pricePerPiece' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'bulkPrice' : IDL.Nat,
  'category' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'whatsapp' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'submitInquiry' : IDL.Func([Inquiry], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'pricePerPiece' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'bulkPrice' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'whatsapp' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitInquiry' : IDL.Func([Inquiry], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };